version: "3"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - /app/node_modules
      - D:\ems-for-organisation\backend:/app/backend
      - D:\ems-for-organisation\frontend:/app/frontend
